### ISSUE TITLE
add TuilX to the list?

### ISSUE THREAD

**Issue by chavacava** [JakobMiksch/go-geospatial#3]
Hi, some time ago I've developed [TuilX](https://github.com/chavacava/tuilx), "_an extensible and composable WMTS server_".

TuilX allows you to easily setup a [WMTS](https://en.wikipedia.org/wiki/Web_Map_Tile_Service) server by creating and/or combining tile sources.

**Comment by JakobMiksch** [comment]
great I will add it

**Comment by JakobMiksch** [comment]
added via [7dd69b6](https://github.com/JakobMiksch/go-geospatial/commit/7dd69b690bda4ca618e233a42f31f3520733d370)
